### ISSUE TITLE
The ORF position in the result seems to be different from the real ORF

### ISSUE THREAD

**Issue by clsteam** [mlin/PhyloCSF#29]
1. This is my mRNA fasta sequence:
`>Luc01.10.1
AGGGCTGTCCTGCTTCTACAAGTGACAATGACAAATATAGGCCTGAAGGAAGATGAGCTGATGGCATTCCCAGCTTACTACCACTCCTTGGGTGCCTTATCTCACATACGTGGATTCAACTCATAGACTCAGCGGTCGGCAAACATGTGACAGGTGGAGGTCCTGAGGCACCACTGGGAGCTTGTGAGCGGATGGGCGTCTTCCAGAACGCACTCTGCAGGCACTCGGCAACGTGAAGTGTTCACGTCCTGTGATGCAGCCTCTGCTCCAGGCCACTTCCGGAA`
2. Then i run **PhyloCSF**:
`
$ cat Luc01.10.1.fa |./PhyloCSF 29mammals --orf=ATGStop --frames=3 --species=Human,Chimp
`
`MSTRG.2.1	max_score(decibans)	10.2675	27	122`
From the results, we can get the maximum value of CSF and ORF is **27-122**，But I use [ORFFinder (NCBI)](https://www.ncbi.nlm.nih.gov/orffinder) to get ORF as **27-125**
4. ORFFinders' ORF: _ATGACAAATATAGGCCTGAAGGAAGATGAGCTGATGGCATTCCCAGCTTACTACCACTCCTTGGGTGCCTTATCTCACATACGTGGATTCAACTCA**TAG**_
5. PhyloCSFs' ORF:
_ATGACAAATATAGGCCTGAAGGAAGATGAGCTGATGGCATTCCCAGCTTACTACCACTCCTTGGGTGCCTTATCTCACATACGTGGATTCAAC**TCA**_
6. But **TCA** is not in the stop codons **TAG, TAA, TGA**，so I wonder if a's result is ORF?

thanks,
yao

**Comment by iljungr** [comment]
When running PhyloCSF on an ORF, it is best to not include the final stop codon (the likelihood ratio for the stop codon is not informative), so when PhyloCSF finds the ORF for you it does not include the final stop codon. The fact that in this case the codon before the stop, TCA, is similar to a stop codon is just a coincidence. The ORF found by PhyloCSF and ORFFinder is the same ORF, just described differently by the two programs -- one with and one without the final stop codon.

**Comment by iljungr** [comment]
By the way, Human and Chimp are too closely related for the PhyloCSF score on only those two species to be meaningful. To get a meaningful score you'd need to include most of the mammal tree. (If you included only those two species in order to simplify the example for reporting the issue, that's fine.)

**Comment by clsteam** [comment]
thanks, i understand
yao
