### ISSUE TITLE
PhyloCSF tracks for GRCm39/mm39 

### ISSUE THREAD

**Issue by vkkodali** [mlin/PhyloCSF#30]
A new mouse genome assembly, GRCm39/mm39, was released last year (https://www.ncbi.nlm.nih.gov/grc/mouse). Recently, UCSC has released multiple alignments of 35 vertebrate species (https://genome.ucsc.edu/cgi-bin/hgTrackUi?db=mm39&g=cons35way). It would be of great use to the research community to generate a new set of PhyloCSF tracks using these new alignments for GRCm39/mm39 assembly.

**Comment by iljungr** [comment]
I plan to do this. In the mean time, these alignments have now been implemented in CodAlignView (https://data.broadinstitute.org/compbio1/cav.php) to see the alignment color coded based on protein-coding constraint. Use the alignment sets mm39_30 for the 30-placental mammal subset and mm39_35 for the full 35 vertebrates.

**Comment by iljungr** [comment]
PhyloCSF browser tracks, including PhyloCSF Candidate Coding Regions for gencode vM26, are now available in the UCSC Genome Browser. They use the 30-placental mammal subset of the 35 vertebrates alignment.

**Comment by vkkodali** [comment]
This is great! Thank you very much.
